/*!
 * Mutation Types
 */

export const LAYOUT_SET_CLIPPED = 'LAYOUT_SET_CLIPPED'
export const LAYOUT_SET_DRAWER = 'LAYOUT_SET_DRAWER'
export const LAYOUT_SET_FIXED = 'LAYOUT_SET_FIXED'
export const LAYOUT_SET_MINIVARIANT = 'LAYOUT_SET_MINIVARIANT'
export const LAYOUT_SET_RIGHT = 'LAYOUT_SET_RIGHT'
export const LAYOUT_SET_RIGHTDRAWER = 'LAYOUT_SET_RIGHTDRAWER'
export const LAYOUT_SET_TITLE = 'LAYOUT_SET_TITLE'

export const STORAGE_SET_ADAPTER = 'STORAGE_SET_ADAPTER'
export const STORAGE_ADD_CONNECTION = 'STORAGE_ADD_CONNECTION'
export const STORAGE_ADD_CONNECTIONS = 'STORAGE_ADD_CONNECTIONS'

export const TWEET_FORM_SET_MESSAGE = 'TWEET_FORM_SET_MESSAGE'
export const TWEET_FORM_ADD_IMAGE = 'TWEET_FORM_ADD_IMAGE'
export const TWEET_FORM_REMOVE_IMAGE = 'TWEET_FORM_REMOVE_IMAGE'
export const TWEET_FORM_SET_REPLY = 'TWEET_FORM_SET_REPLY'
export const TWEET_FORM_RESET = 'TWEET_FORM_RESET'

export const TWITTER_SET_VALIDATED = 'TWITTER_SET_VALIDATED'
export const TWITTER_SET_PROFILE = 'TWITTER_SET_PROFILE'

export const TWITTER_SET_FRIENDS_COUNT = 'TWITTER_SET_FRIENDS_COUNT'
export const TWITTER_SET_FOLLOWERS_COUNT = 'TWITTER_SET_FOLLOWERS_COUNT'
export const TWITTER_SET_STATUSES_COUNT = 'TWITTER_SET_STATUSES_COUNT'
export const TWITTER_SET_FAVORITES_COUNT = 'TWITTER_SET_FAVORITES_COUNT'

export const TWITTER_LISTS_SAVED = 'TWITTER_LISTS_SAVED'
export const TWITTER_LISTS_ACTIVE = 'TWITTER_LISTS_ACTIVE'
export const TWITTER_LISTS_DELETE_LOCAL = 'TWITTER_LISTS_DELETE_LOCAL'
export const TWITTER_LISTS_DELETE_REMOTE = 'TWITTER_LISTS_DELETE_REMOTE'
export const TWITTER_LISTS_UPDATE_LOCAL = 'TWITTER_LISTS_UPDATE_LOCAL'
export const TWITTER_LISTS_UPDATE_REMOTE = 'TWITTER_LISTS_UPDATE_REMOTE'

export const TWITTER_USERS_LOAD_FRIENDS = 'TWITTER_USERS_LOAD_FRIENDS'
export const TWITTER_USERS_LOAD_FOLLOWERS = 'TWITTER_USERS_LOAD_FOLLOWERS'
export const TWITTER_USERS_FRIENDSHIP_CREATE = 'TWITTER_USERS_FRIENDSHIP_CREATE'
export const TWITTER_USERS_FRIENDSHIP_DESTROY = 'TWITTER_USERS_FRIENDSHIP_DESTROY'

export const STATUS_TIMELINE_LOAD_HOME = 'STATUS_TIMELINE_LOAD_HOME'
export const STATUS_TIMELINE_STREAM_HOME = 'STATUS_TIMELINE_STREAM_HOME'
export const STATUS_TIMELINE_LOAD_USER = 'STATUS_TIMELINE_LOAD_USER'
export const STATUS_TIMELINE_LOAD_FAVS = 'STATUS_TIMELINE_LOAD_FAVS'

export const STATUS_TWEET_DESTROY = 'STATUS_TWEET_DESTROY'
export const STATUS_TWEET_CREATE = 'STATUS_TWEET_CREATE'
export const STATUS_FAVORITES_CREATE = 'STATUS_FAVORITES_CREATE'
export const STATUS_FAVORITES_DESTROY = 'STATUS_FAVORITES_DESTROY'
export const STATUS_RETWEET_CREATE = 'STATUS_RETWEET_CREATE'
export const STATUS_RETWEET_DESTROY = 'STATUS_RETWEET_DESTROY'

export const TASKS_SET_PROGRESS = 'TASKS_SET_PROGRESS'
export const TASKS_RESET_PROGRESS = 'TASKS_RESET_PROGRESS'

export const LOOKUP_USERS_SEARCH = 'LOOKUP_USERS_SEARCH'
export const LOOKUP_USERS_LOOKUP = 'LOOKUP_USERS_LOOKUP'
export const LOOKUP_USERS_REMOVE = 'LOOKUP_USERS_REMOVE'
export const LOOKUP_USERS_CLEAR = 'LOOKUP_USERS_CLEAR'
export const LOOKUP_USERS_FRIENDSHIP = 'LOOKUP_USERS_FRIENDSHIP'

export const SEARCH_SESSION_ACTIVE = 'SEARCH_SESSION_ACTIVE'
export const SEARCH_SESSION_SAVE = 'SEARCH_SESSION_SAVE'
export const SEARCH_SESSION_START = 'SEARCH_SESSION_START'
export const SEARCH_SESSION_END = 'SEARCH_SESSION_END'
export const SEARCH_SESSION_GRID = 'SEARCH_SESSION_GRID'
export const SEARCH_SESSION_UPDATE = 'SEARCH_SESSION_UPDATE'
export const SEARCH_SESSION_DELETE = 'SEARCH_SESSION_DELETE'

export const TRENDS_MODAL_DIALOG = 'TRENDS_MODAL_DIALOG'
export const TRENDS_LOAD_AVAILABLE = 'TRENDS_LOAD_AVAILABLE'
export const TRENDS_LOAD_CLOSEST = 'TRENDS_LOAD_CLOSEST'
export const TRENDS_LOAD_PLACE = 'TRENDS_LOAD_PLACE'

export const EXPUNGE_LOAD_TWEETS = 'EXPUNGE_LOAD_TWEETS'
export const EXPUNGE_LOAD_FAVORITES = 'EXPUNGE_LOAD_FAVORITES'
export const EXPUNGE_RESET_TWEETS = 'EXPUNGE_RESET_TWEETS'
export const EXPUNGE_RESET_FAVORITES = 'EXPUNGE_RESET_FAVORITES'
export const EXPUNGE_DESTROY_TWEET = 'EXPUNGE_DESTROY_TWEET'
export const EXPUNGE_DESTROY_FAVORITE = 'EXPUNGE_DESTROY_FAVORITE'
export const EXPUNGE_SET_SELECTED = 'EXPUNGE_SET_SELECTED'
export const EXPUNGE_RESET_SELECTED = 'EXPUNGE_RESET_SELECTED'
