export const API_STORAGE_SQLITE = 'sqlite3'
export const API_STORAGE_MYSQL = 'mysql'
export const API_STORAGE_POSTGRES = 'postgres'
export const API_STORAGE_MARIADB = 'mariadb'
export const API_STORAGE_ORACLE = 'oracle'
export const API_STORAGE_MSSQL = 'mssql'
export const API_STORAGE_POUCHDB = 'pouchdb'

// ipc-main/renderer
export const IPC_REQUEST_SCHEMA_CREATE = 'IPC_REQUEST_SCHEMA_CREATE'
export const IPC_RESPONSE_SCHEMA_CREATE = 'IPC_RESPONSE_SCHEMA_CREATE'
export const IPC_REQUEST_SCHEMA_CONFIG = 'IPC_REQUEST_SCHEMA_CONFIG'
export const IPC_RESPONSE_SCHEMA_CONFIG = 'IPC_RESPONSE_SCHEMA_CONFIG'
export const IPC_REQUEST_TWITTER_SETTINGS = 'IPC_REQUEST_TWITTER_SETTINGS'
export const IPC_RESPONSE_TWITTER_SETTINGS = 'IPC_RESPONSE_TWITTER_SETTINGS'
export const IPC_REQUEST_TWITTER_CREDENTIALS = 'IPC_REQUEST_TWITTER_CREDENTIALS'
export const IPC_RESPONSE_TWITTER_CREDENTIALS = 'IPC_RESPONSE_TWITTER_CREDENTIALS'

// search opts/settings
export const SEARCH_SETTINGS_INCLUDE = 'SEARCH_SETTINGS_INCLUDE'
export const SEARCH_SETTINGS_EXCLUDE = 'SEARCH_SETTINGS_EXCLUDE'
export const SEARCH_SETTINGS_LIMITED = 'SEARCH_SETTINGS_LIMITED'
